name: Build and Push Docker images

on:
  push:
    branches: ["main"] # push latest на main
    tags: ["v*"] # push тегов v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Настройка мультиархитектурной сборки
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      # Логин в Docker Hub
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build и push обычного образа (python:3.11-slim)
      - name: Build and Push (main)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            v1lex/mini-shell:latest
            v1lex/mini-shell:${{ github.ref_name }}

      # Build и push Distroless
      - name: Build and Push (distroless)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: dockerfile.distroless
          platforms: linux/amd64,linux/arm64
          push: true
          tags: v1lex/mini-shell:distroless
